// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: Config.firebaseWebApiKey,
    appId: Config.firebaseWebAppId,
    messagingSenderId: Config.firebaseWebMessagingSenderId,
    projectId: Config.firebaseWebProjectId,
    authDomain: Config.firebaseWebAuthDomain,
    storageBucket: Config.firebaseWebStorageBucket,
    measurementId: Config.firebaseWebMeasurementId,
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: Config.firebaseAndroidApiKey,
    appId: Config.firebaseAndroidAppId,
    messagingSenderId: Config.firebaseAndroidMessagingSenderId,
    projectId: Config.firebaseAndroidProjectId,
    storageBucket: Config.firebaseAndroidStorageBucket,
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: Config.firebaseIosApiKey,
    appId: Config.firebaseIosAppId,
    messagingSenderId: Config.firebaseIosMessagingSenderId,
    projectId: Config.firebaseIosProjectId,
    storageBucket: Config.firebaseIosStorageBucket,
    iosBundleId: Config.iosBundleId,
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: Config.firebaseMacosApiKey,
    appId: Config.firebaseMacosAppId,
    messagingSenderId: Config.firebaseMacosMessagingSenderId,
    projectId: Config.firebaseMacosProjectId,
    storageBucket: Config.firebaseMacosStorageBucket,
    iosBundleId: Config.iosBundleId,
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: Config.firebaseWindowsApiKey,
    appId: Config.firebaseWindowsAppId,
    messagingSenderId: Config.firebaseWindowsMessagingSenderId,
    projectId: Config.firebaseWindowsProjectId,
    authDomain: Config.firebaseWebAuthDomain,
    storageBucket: Config.firebaseWindowsStorageBucket,
    measurementId: Config.firebaseWindowsMeasurementId,
  );
}
