// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg-Jud13I-zfvRUXJvaM2fOBVN97lmwqQ',
    appId: '1:587639520564:web:57c740881fc7ca17367961',
    messagingSenderId: '587639520564',
    projectId: 'genie-on-call',
    authDomain: 'genie-on-call.firebaseapp.com',
    storageBucket: 'genie-on-call.firebasestorage.app',
    measurementId: 'G-KH3Y5TDY3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArT2kayftUu0VIRNuUmslkep11cNPn3K8',
    appId: '1:341283748050:android:d9c6e4f71e11411047d50b',
    messagingSenderId: '341283748050',
    projectId: 'genie-on-call-769a1',
    storageBucket: 'genie-on-call-769a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs_4doLoR2SsbATUpIo8yUoTdYBWsO_kw',
    appId: '1:587639520564:ios:22fa95ee5389faa0367961',
    messagingSenderId: '587639520564',
    projectId: 'genie-on-call',
    storageBucket: 'genie-on-call.firebasestorage.app',
    iosBundleId: 'com.example.genieOnCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs_4doLoR2SsbATUpIo8yUoTdYBWsO_kw',
    appId: '1:587639520564:ios:22fa95ee5389faa0367961',
    messagingSenderId: '587639520564',
    projectId: 'genie-on-call',
    storageBucket: 'genie-on-call.firebasestorage.app',
    iosBundleId: 'com.example.genieOnCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg-Jud13I-zfvRUXJvaM2fOBVN97lmwqQ',
    appId: '1:587639520564:web:a53550f0eddbdd31367961',
    messagingSenderId: '587639520564',
    projectId: 'genie-on-call',
    authDomain: 'genie-on-call.firebaseapp.com',
    storageBucket: 'genie-on-call.firebasestorage.app',
    measurementId: 'G-02973MW57V',
  );
}